// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXpI7wcKDVrknYrCrpRW3NKbDFhwBHAxY',
    appId: '1:942554870984:web:562d1682d7c75ad132a1fd',
    messagingSenderId: '942554870984',
    projectId: 'ecommerce-app-12c8c',
    authDomain: 'ecommerce-app-12c8c.firebaseapp.com',
    storageBucket: 'ecommerce-app-12c8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-CYlLDQuw70ySLZuvBHK9yJhr_BKY7uQ',
    appId: '1:942554870984:android:1f8f30821bb9a83632a1fd',
    messagingSenderId: '942554870984',
    projectId: 'ecommerce-app-12c8c',
    storageBucket: 'ecommerce-app-12c8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35LGMaJQWdUTLlyAXoozsvIA6yv5Oz1c',
    appId: '1:942554870984:ios:75a314b76823869732a1fd',
    messagingSenderId: '942554870984',
    projectId: 'ecommerce-app-12c8c',
    storageBucket: 'ecommerce-app-12c8c.firebasestorage.app',
    androidClientId: '942554870984-7tutk5bkqv3pp6a6jqb1048u8bmaumur.apps.googleusercontent.com',
    iosClientId: '942554870984-6m1a4fa7cuqt8goe9gkb77pcrpuim65p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:7b67fa8db6b2840d0653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    databaseURL: 'https://codingwitht-c6d0f-default-rtdb.firebaseio.com',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    androidClientId: '823307041176-kun16mo723tugpbptbcbupndhaubv8cn.apps.googleusercontent.com',
    iosClientId: '823307041176-lp36pj2a155ifcmkeil3p2ch72krur3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXpI7wcKDVrknYrCrpRW3NKbDFhwBHAxY',
    appId: '1:942554870984:web:9a571fdc6b3f878832a1fd',
    messagingSenderId: '942554870984',
    projectId: 'ecommerce-app-12c8c',
    authDomain: 'ecommerce-app-12c8c.firebaseapp.com',
    storageBucket: 'ecommerce-app-12c8c.firebasestorage.app',
  );

}